environment:
  FSACVERSION: 0.34.0
  FSharpBinding_BlockingTimeout: 1000
  FSharpBinding_MaxTimeout: 10000
matrix:
  fast_finish: true
install:
  - ps: Start-FileDownload "https://github.com/fsharp/FSharp.AutoComplete/releases/download/$env:FSACVERSION/fsautocomplete.zip"
  - ps: 7z x fsautocomplete.zip -oemacs-fsharp-mode\bin | select-string -notmatch "ing  "
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install coreutils
  - ps: scoop install make
  - ps: scoop install grep
  - ps: scoop install unzip
  - ps: scoop bucket add extras
  - ps: scoop install emacs
  - ps: scoop bucket add versions
  - ps: scoop install python27
  - ps: scoop install dotnet-sdk
  - ps: Start-FileDownload "https://raw.githubusercontent.com/cask/cask/master/go"
  - ps: python go
build_script:
  - cmd: .\.appveyor\test.bat
test: off
 
